spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movie
    username: postgresql
    password: example
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    properties:
      hibernate:
        default_schema: public
        jdbc:
          lob:
            non_contextual_creation: true

logging:
  level:
    root: info

server:
  port: 8080
